### ISSUE TITLE
Migrate from Maven to Grunt

### ISSUE THREAD

**Issue by jankeesvanandel** [devoxx/cfp-speaker#3]
Maven is useless in this kind of environment. We only used it because we know it well. But it's inappropriate for this kind of application.
- Set up build scripts/config
- Change directory structure to match with Grunt conventions

**Comment by clakech** [comment]
:+1: I fall in love with this issue, this could really help us to create multiple web sites, incorporating multiple app, sharing behavior, rendering, controller, services and web components/UI!
