### ISSUE TITLE
Add tags requires 2 enters, this is not intuitive

### ISSUE THREAD

**Issue by jayv** [devoxx/cfp-speaker#30]

**Comment by jankeesvanandel** [comment]
fixed #30  - By increasing priority of devoxxOnReturnKey to make sure that the jQuery event handler underneath fires before the bootstrap one, then yielding the event handling using $timeout, to make sure that the bootstrap event handler has time to do its typeahead magic and let angular run all digest cycles needed, then kicking in to let the event handler fire (also changed keypress to keydown)
