### ISSUE TITLE
NPE When updating a proposal (was:Editing an already submitted proposal creates a new proposal)

### ISSUE THREAD

**Issue by peterkuterna** [devoxx/cfp-speaker#38]
I enter a proposal and submit this one.
I list all my proposal.
I click on the edit button.
I change something and submit again.
This creates a new proposal.

**Comment by jayv** [comment]
The client didn't send the ID  and didn't use the correct method, I've fixed that, but now the server errors with a 500:

`{"message":null,"exceptionType":"classjava.lang.NullPointerException"}`

**Comment by mikeseghers** [comment]
Do you also send the version property?

**Comment by jayv** [comment]
No, should I?

**Comment by mikeseghers** [comment]
Yes, since otherwise we would compromise the optimistic locking system...
