### ISSUE TITLE
Bars & restaurant links are not working

### ISSUE THREAD

**Issue by timpeeters** [devoxx/cfp-speaker#39]
On the venue page, the bars & restaurants at the bottom right are not working.
http://cfp-speaker-staging.devoxx.eu.cloudbees.net/#/venue

**Comment by jayv** [comment]
There are no HREFs, could you add the URLs and send a pull request? ;-)

**Comment by timpeeters** [comment]
https://github.com/devoxx/cfp-speaker/pull/45
