### ISSUE TITLE
New Proposal submission: Error remains after all fields filled in

### ISSUE THREAD

**Issue by daniel-deluca** [devoxx/cfp-speaker#41]
Scenario: 
1: Entering new proposal
2: Filling all fields (in order top down)
   DevoxxUK 
   BOF
   Future<Devoxx>
   Novice
   testDaniel-2013-06-06-02
   testDaniel-2013-06-06-02
   testDaniel-2013-06-06-02
   Test
   Daniel De Luca
   Checked
    Checked
3: Error displayed and remains.
"The proposal is incomplete, all field are mandatory except for the private message. Be sure to verify the number of tags, speakers and the length of the summary is withing the given limits."
Impossible to submit.

Browser: Chrome Version 27.0.1453.110
OS: Mac OSX 10.8.3
Date time: 2013-06-06 19:14

**Comment by jayv** [comment]
There is a minimum of 10 characters on the summary, it would be a bit silly to mention this on the page. Although 10 should probably be like 100 or so.

**Comment by daniel-deluca** [comment]
Jo,
Still, when entering more text (6 character left) I do still have the issue.
Question: Normal that I can entire more text than allowed ? (I've tried and I went to -1812 characters left)  ;-)

**Comment by daniel-deluca** [comment]
Testing again with a fresh started browser (Safari in this case) I'm having the exact same behaviour.

**Comment by daniel-deluca** [comment]
Also, when trying to add speakers... does not work.
I can remove myself (click on the X under my picture) but I can't add speakers.
