### ISSUE TITLE
termsAndConditions boolean is not included in XHR POST/PUT

### ISSUE THREAD

**Issue by stephanj** [devoxx/cfp-speaker#52]
The terms and conditions boolean is not included in the XHR POST/PUT

**Comment by stephanj** [comment]
Or is the logic that you can't submit until you select the Terms, as a result it has been selected?!

**Comment by jayv** [comment]
Don't know if this is expected behavior but today it's not submitted and it forces you to tick the box each time to submit.

**Comment by stephanj** [comment]
This is fine!
