### ISSUE TITLE
Integrate CFP app in new Devoxx site

### ISSUE THREAD

**Issue by jankeesvanandel** [devoxx/cfp-speaker#6]
The current CFP app integrates both main layout and itself.

We still need to figure out a way to integrate this into the devoxx site, preferrably without duplicating a lot of markup.

One way could be server side rendering a couple of template html pages. (of maybe build time rendering the pages for runtime performance) This way, the content is reused along all modules, but the modules are independent.

**Comment by clakech** [comment]
:+1: 

is devoxx sites code available ? or private ?

**Comment by jayv** [comment]
The gruntjs assemble plugin could be used to integrate multiple apps
